apiVersion: v1
kind: Service
metadata:
  name: devframe-web-apache-service
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: devframe-web-apache
  type: NodePort